-- AlterTable
ALTER TABLE "ReadingProgress" ADD COLUMN     "chapterId" TEXT,
ADD COLUMN     "lastReadAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "scrollPosition" DOUBLE PRECISION NOT NULL DEFAULT 0;
